### PR TITLE
[best-practices] - Don't use id as a type

### LINKED ISSUE #27: Avoid using id as type
The `id` type is dangerous and should be avoided. Instead use one of the following
- concrete type e.g. `NSString`
- `instancetype`
- generics `id<Type>`

### PR DESCRIPTION
**Pull request by kostiakoval**
Fix #27

### CODE REVIEW

**Comment by kostiakoval** [comment]
Like that? @hfossli

**Comment by hfossli** [comment]
👌

**Comment by kostiakoval** [comment]
@agensdev/ios any other wants to say any feedback?

**Comment by kostiakoval** [comment]
😱 Very good point! Would be better to have example with `init` method or just a regular instance method?

**Comment by hfossli** [comment]
Both maybe?

**Comment by kostiakoval** [comment]
Agree! also what about the examples itself, should the show the "how not to do" or how to do right?

**Pull request merged**
